const githubService = require('../services/githubService');
const notionService = require('../services/notionService');
const aiService = require('../services/aiService');
const logger = require('../utils/logger');
const { slugifyTitle } = require('../utils/helpers');

class SyncController {
  /**
   * Main sync endpoint - orchestrates the entire sync process
   */
  async syncSolution(req, res, next) {
    try {
      const { 
        problemTitle, 
        difficulty, 
        code, 
        language, 
        userApiKey,
        tags = [],
        problemUrl = ''
      } = req.body;

      logger.info(`Starting sync for problem: ${problemTitle}`);

      // Step 1: Generate AI summary (using user's API key)
      let aiSummary = null;
      try {
        aiSummary = await aiService.generateSummary({
          problemTitle,
          code,
          difficulty,
          language,
          userApiKey
        });
        logger.info('AI summary generated successfully');
      } catch (error) {
        logger.warn(`AI summary generation failed: ${error.message}`);
        // Continue without AI summary
        aiSummary = {
          summary: 'AI summary unavailable',
          approach: 'N/A',
          timeComplexity: 'N/A',
          spaceComplexity: 'N/A'
        };
      }

      // Step 2: Create slug for folder structure
      const slug = slugifyTitle(problemTitle);

      // Step 3: Generate README content
      const readmeContent = this.generateReadme({
        problemTitle,
        difficulty,
        language,
        aiSummary,
        tags,
        problemUrl
      });

      // Step 4: Push to GitHub
      let githubUrl = null;
      try {
        githubUrl = await githubService.pushSolution({
          slug,
          code,
          language,
          readme: readmeContent,
          problemTitle
        });
        logger.info(`Pushed to GitHub: ${githubUrl}`);
      } catch (error) {
        logger.error(`GitHub push failed: ${error.message}`);
        throw new Error(`Failed to push to GitHub: ${error.message}`);
      }

      // Step 5: Create Notion entry
      let notionUrl = null;
      try {
        notionUrl = await notionService.createEntry({
          problemTitle,
          difficulty,
          tags,
          githubUrl,
          aiSummary,
          language,
          problemUrl
        });
        logger.info(`Created Notion entry: ${notionUrl}`);
      } catch (error) {
        logger.warn(`Notion creation failed: ${error.message}`);
        // Continue even if Notion fails
      }

      // Success response
      res.status(200).json({
        success: true,
        message: 'Solution synced successfully',
        data: {
          githubUrl,
          notionUrl,
          aiSummary: aiSummary.summary,
          slug
        }
      });

    } catch (error) {
      logger.error(`Sync failed: ${error.message}`);
      next(error);
    }
  }

  /**
   * Validate backend configuration
   */
  async validateConfig(req, res) {
    const config = {
      github: !!process.env.GITHUB_TOKEN && !!process.env.GITHUB_USERNAME,
      notion: !!process.env.NOTION_API_KEY && !!process.env.NOTION_DATABASE_ID,
      server: true
    };

    const allValid = Object.values(config).every(v => v === true);

    res.status(200).json({
      success: true,
      valid: allValid,
      config
    });
  }

  /**
   * Generate README.md content
   */
  generateReadme({ problemTitle, difficulty, language, aiSummary, tags, problemUrl }) {
    return `# ${problemTitle}

## Problem Details
- **Difficulty:** ${difficulty}
- **Language:** ${language}
${tags.length > 0 ? `- **Tags:** ${tags.join(', ')}` : ''}
${problemUrl ? `- **Problem Link:** [LeetCode](${problemUrl})` : ''}

## Solution Summary
${aiSummary.summary}

## Approach
${aiSummary.approach}

## Complexity Analysis
- **Time Complexity:** ${aiSummary.timeComplexity}
- **Space Complexity:** ${aiSummary.spaceComplexity}

## Solution
See \`solution.${this.getFileExtension(language)}\` in this directory.

---
*Generated by LeetCode Auto Sync*
`;
  }

  /**
   * Get file extension based on language
   */
  getFileExtension(language) {
    const extensions = {
      'javascript': 'js',
      'python': 'py',
      'python3': 'py',
      'java': 'java',
      'c++': 'cpp',
      'c': 'c',
      'c#': 'cs',
      'ruby': 'rb',
      'swift': 'swift',
      'go': 'go',
      'kotlin': 'kt',
      'rust': 'rs',
      'typescript': 'ts'
    };
    return extensions[language.toLowerCase()] || 'txt';
  }
}

module.exports = new SyncController();
